# Based on https://github.com/CTeX-org/ctex-kit/blob/master/.github/workflows/test.yml

name: Test tabularray in TeX Live

on: [push, pull_request]

env:
  TLCurrent: https://mirrors.rit.edu/CTAN/systems/texlive/tlnet
  TLHistoric: https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2021/tlnet-final

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install TeX Live
      run: |
        export PATH=${{github.workspace}}/tmp/texlive/bin/x86_64-linux:$PATH
        wget ${{env.TLCurrent}}/install-tl-unx.tar.gz
        tar -xzf install-tl-unx.tar.gz
        cd install-tl-20*
        ./install-tl --profile ../.github/workflows/texlive.profile --repository=${{env.TLCurrent}}
        echo $(cat ${{github.workspace}}/.github/workflows/texlive.package) | xargs tlmgr install
        tlmgr update --self --all --no-auto-install --repository=${{env.TLCurrent}}
    - name: Test tabularray with l3build
      run: |
        export PATH=${{github.workspace}}/tmp/texlive/bin/x86_64-linux:$PATH
        l3build check --debug --halt-on-error --show-log-on-error
    - name: Install pdftoppm
      run:
        sudo apt-get install poppler-utils
    - name: Test tabularray with ppmcheck
      run: |
        export PATH=${{github.workspace}}/tmp/texlive/bin/x86_64-linux:$PATH
        texlua ppmcheck.lua
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install TeX Live
      run: |
        ${env:PATH} = "${{github.workspace}}\tmp\texlive\bin\win32;" + ${env:PATH}
        Invoke-WebRequest -Uri ${{env.TLCurrent}}/install-tl.zip -OutFile install-tl.zip
        Expand-Archive install-tl.zip -DestinationPath .
        Set-Location install-tl-*
        .\install-tl-windows --no-gui --profile ..\.github\workflows\texlive.profile --repository=${{env.TLCurrent}}
        ${{github.workspace}}/.github/workflows/texlive.bat
        tlmgr update --self --all --no-auto-install --repository=${{env.TLCurrent}}
    - name: Test tabularray with l3build
      run: |
        ${env:PATH} = "${{github.workspace}}\tmp\texlive\bin\win32;" + ${env:PATH}
        l3build check --debug --halt-on-error --show-log-on-error
    - name: Install pdftoppm
      run: |
        ${env:PATH} = "${{github.workspace}}\tmp\texlive\bin\win32;" + ${env:PATH}
        tlmgr install wintools.win32
    - name: Test tabularray with ppmcheck
      run: |
        ${env:PATH} = "${{github.workspace}}\tmp\texlive\bin\win32;" + ${env:PATH}
        texlua ppmcheck.lua
    - name: Upload updated png and md5
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: png-and-md5
        path: |
          build/test/updated/*.*
